# Generated by Django 4.0.4 on 2022-06-03 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('nome_da_rua', models.CharField(max_length=60)),
                ('numero_da_casa', models.IntegerField()),
                ('complemento', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('cep', models.IntegerField()),
                ('celular', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('data_procedimento', models.DateField(primary_key=True, serialize=False)),
                ('numero_da_carteirinha', models.CharField(max_length=15)),
                ('valor', models.DecimalField(decimal_places=13, max_digits=15)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.paciente')),
            ],
            options={
                'db_table': 'procedimento',
            },
        ),
    ]
