# Generated by Django 4.0.5 on 2022-06-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('ano_de_nascimento', models.DateField()),
                ('ano_de_contratacao', models.DateField()),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
    ]
